version: "3.2"

services:
    phing-service:
        image: mybb-build
        build:
            context: .
        volumes:
            - ./sources:/home/user/sources/:ro
            - ./output:/home/user/output/
