version: "3.2"
services:
  phing:
    image: mybb-build
    build:
      context: ${PWD}
    env_file:
      - secrets.env
    volumes:
      - ${PWD}/input:/home/user/input/
      - ${PWD}/output:/home/user/output/
      - ${PWD}/secrets:/home/user/secrets/:ro
