version: "3.2"

services:
    phing:
        image: mybb-build
        build:
            context: .
        volumes:
            - ./input:/home/user/input/:ro
            - ./output:/home/user/output/
